/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmapNearby: typeof import('./src/components/AmapNearby.vue')['default']
    AppFooter: typeof import('./src/components/Layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/Layout/AppHeader.vue')['default']
    CompareBar: typeof import('./src/components/CompareBar.vue')['default']
    ConfirmModal: typeof import('./src/components/ConfirmModal.vue')['default']
    FavoriteButton: typeof import('./src/components/FavoriteButton.vue')['default']
    FavoriteNotification: typeof import('./src/components/FavoriteNotification.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
    PropertyCard: typeof import('./src/components/PropertyCard.vue')['default']
    PropertyFilter: typeof import('./src/components/PropertyFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.0_async-validator@4.2.5_change-case@5.4.4_embla-carou_4138c946a49e353f813d86cc9285cb8c/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.0_async-validator@4.2.5_change-case@5.4.4_embla-carou_4138c946a49e353f813d86cc9285cb8c/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.0_async-validator@4.2.5_change-case@5.4.4_embla-carou_4138c946a49e353f813d86cc9285cb8c/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDropdownMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.0_async-validator@4.2.5_change-case@5.4.4_embla-carou_4138c946a49e353f813d86cc9285cb8c/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.0_async-validator@4.2.5_change-case@5.4.4_embla-carou_4138c946a49e353f813d86cc9285cb8c/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.0_async-validator@4.2.5_change-case@5.4.4_embla-carou_4138c946a49e353f813d86cc9285cb8c/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.0_async-validator@4.2.5_change-case@5.4.4_embla-carou_4138c946a49e353f813d86cc9285cb8c/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.0_async-validator@4.2.5_change-case@5.4.4_embla-carou_4138c946a49e353f813d86cc9285cb8c/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.0_async-validator@4.2.5_change-case@5.4.4_embla-carou_4138c946a49e353f813d86cc9285cb8c/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.0_async-validator@4.2.5_change-case@5.4.4_embla-carou_4138c946a49e353f813d86cc9285cb8c/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  }
}
