/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmapNearby: typeof import('./components/AmapNearby.vue')['default']
    AppFooter: typeof import('./components/Layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/Layout/AppHeader.vue')['default']
    CompareBar: typeof import('./components/CompareBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    FavoriteButton: typeof import('./components/FavoriteButton.vue')['default']
    FavoriteNotification: typeof import('./components/FavoriteNotification.vue')['default']
    ImageGallery: typeof import('./components/ImageGallery.vue')['default']
    ImageViewer: typeof import('./components/ImageViewer.vue')['default']
    PropertyCard: typeof import('./components/PropertyCard.vue')['default']
    PropertyFilter: typeof import('./components/PropertyFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
